### PR TITLE
[MRM-1861] Proxy behaviour issue migrating from 1.3.x to 2.x

### PR DESCRIPTION
**Pull request by emsouza**

### CODE REVIEW

**Comment by ebarboni** [comment]
The PR was good, error was because of failling test on other modules.
I don't know how to merge :(

**Comment by olamy** [comment]
@ebarboni 
vi .git/config
add those lines
[remote "github"]
      url = https://github.com/apache/archiva.git
        fetch = +refs/heads/*:refs/remotes/github/*
        fetch = +refs/pull/*/head:refs/pull/upstream/*


git fetch github
git checkout pr/16
test it
then git checkout master
git merge pr/16
then git push origin master
if origin is the apache git

**Comment by ebarboni** [comment]
@olamy, thanks a lot, (I was looking for some button or UI on the github web site for merging)

**Comment by olamy** [comment]
@ebarboni Nope as github is not the primary git repo.

**Comment by hugosenari** [comment]
Only for the record.
I tested this version (master), and don't solves my problem.
I don't know if is another problem with proxy or is same that still unsolved.

With old version my logs looks similar to bug description (timeout) now is different (auth error)
If help, here is [my log](https://gist.github.com/hugosenari/3ffca9ddac4e3c5f256b).

**Pull request merged**
